### ISSUE TITLE
Implement Claim Batching - debug storage issue

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#205]
part of #142 

During reading, the storage seems to be correctly storing the hash to download, but during the download attempt in the ClaimController class, the method `downloadEntryClaim` is throwing an error. 

Spent a couple hours on this last night, going to continue today. not sure if this was introduced yet by the claim batching branch or via the master branch.

Here is the error output

```
[2] [2018-07-03T20:59:58.545Z] ERROR (1844 on Kenneths-MacBook-Pro.local): Uncaught Error Downloading Next Hash
[2]     module: "Storage"
[2]     file: "Service"
[2]     method: "downloadNextHash"
[2]     error: {
[2]       "stack": [
[2]         "TypeError [ERR_INVALID_ARG_TYPE]: The \"string\" argument must be one of type string, Buffer, or ArrayBuffer. Received type number",
[2]         "    at Function.byteLength (buffer.js:514:11)",
[2]         "    at BufferWriter.write_string_buffer [as string] (/Users/kennethlavender/projects/poet/node/node_modules/protobufjs/src/writer_buffer.js:68:22)",
[2]         "    at Type.Attribute$encode [as encode] (eval at Codegen (/Users/kennethlavender/projects/poet/node/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:9:16)",
[2]         "    at Type.Claim$encode [as encode] (eval at Codegen (/Users/kennethlavender/projects/poet/node/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:18:12)",
[2]         "    at Object.claimToHex (/Users/kennethlavender/projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Serialization.js:34:50)",
[2]         "    at getClaimId (/Users/kennethlavender/projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Claim.js:10:62)",
[2]         "    at Object.exports.isValidClaim (/Users/kennethlavender/projects/poet/node/node_modules/@po.et/poet-js/dist/babel/src/Claim.js:46:100)",
[2]         "    at ClaimController.downloadEntryClaim (/Users/kennethlavender/projects/poet/node/dist/babel/src/Storage/ClaimController.js:97:28)",
[2]         "    at process._tickCallback (internal/process/next_tick.js:68:7)"
[2]       ],
[2]       "message": "The \"string\" argument must be one of type string, Buffer, or ArrayBuffer. Received type number",
[2]       "code": "ERR_INVALID_ARG_TYPE",
[2]       "type": "NodeError"
[2]     }
[2] [2018-0
```

**Comment by kennylavender** [comment]
It is throwing here on this line: https://github.com/poetapp/node/blob/master/src/Storage/ClaimController.ts#L238

It is not from the claim batching pr, but I will double check to make sure the claims I stamped were correctly formatted first.

**Comment by kennylavender** [comment]
I believe isValidClaim was returning false because I use a UTC timestamp instead of an ISO string for the dates. Trying now with ISO strings

**Comment by kennylavender** [comment]
Yup the time format was the cause. Works now.
