### ISSUE TITLE
Docker-compose up --build not setting up mongo

### ISSUE THREAD

**Issue by geoffturk** [poetapp/node#556]
I got the following error after running `docker-compose up --build` on the master branch.

Is the DB script not being run to create the accounts before node connects to mongo?

```
mongo_1       | 2018-10-13T07:50:57.380+0000 I NETWORK  [thread1] connection accepted from 172.18.0.6:42524 #6 (1 connection now open)
mongo_1       | 2018-10-13T07:50:57.383+0000 I NETWORK  [conn6] received client metadata from 172.18.0.6:42524 conn6: { driver: { name: "nodejs", version: "3.1.8" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-135-generic" }, platform: "Node.js v10.12.0, LE, mongodb-core: 3.1.7" }
mongo_1       | 2018-10-13T07:50:57.384+0000 I ACCESS   [conn6] SCRAM-SHA-1 authentication failed for poet on poet from client 172.18.0.6:42524 ; UserNotFound: Could not find user poet@poet
mongo_1       | 2018-10-13T07:50:57.385+0000 I -        [conn6] end connection 172.18.0.6:42524 (1 connection now open)
poet-node_1   | [2018-10-13T07:50:57.385Z] ERROR (18 on a3a6bac7d7c8): BlockchainReader was unable to start
poet-node_1   |     exception: {
poet-node_1   |       "ok": 0,
poet-node_1   |       "errmsg": "Authentication failed.",
poet-node_1   |       "code": 18,
poet-node_1   |       "codeName": "AuthenticationFailed",
poet-node_1   |       "name": "MongoError",
poet-node_1   |       "stack": [
poet-node_1   |         "MongoError: Authentication failed.",
poet-node_1   |         "    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:581:63",
poet-node_1   |         "    at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:504:16)",
poet-node_1   |         "    at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:540:5)",
poet-node_1   |         "    at emitMessageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:310:10)",
poet-node_1   |         "    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:453:17)",
poet-node_1   |         "    at Socket.emit (events.js:182:13)",
poet-node_1   |         "    at addChunk (_stream_readable.js:283:12)",
poet-node_1   |         "    at readableAddChunk (_stream_readable.js:264:11)",
poet-node_1   |         "    at Socket.Readable.push (_stream_readable.js:219:10)",
poet-node_1   |         "    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)"
poet-node_1   |       ],
poet-node_1   |       "message": "Authentication failed.",
poet-node_1   |       "type": "MongoError"
poet-node_1   |     }
node_poet-node_1 exited with code 0
```

**Comment by warrenv** [comment]
Try running 'docker volume prune' or delete the database volume.
The name of the database has changed from poet to poet-dev.
This get created automatically by the mongo conainer startup, but when the volume gets created bucause there isn't one.

**Comment by geoffturk** [comment]
Old volumes was the issue. It runs fine now.
