### ISSUE TITLE
Watch does not work from inside docker container

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#600]
from local-dev, node modules are deleted from previous installs

```
cp docker-compose.override.yml.example docker-compose.override.yml
```

uncomment poet-node lines in docker-compose.override.yml

```
docker-compose up -d poet-node
docker-compose exec poet-node bash
npm i
npm run watch
```

results in

```
...
[1] dist/ts/test/Claims.js -> dist/babel/test/Claims.js
[1] dist/ts/test/Integration/GetWork.js -> dist/babel/test/Integration/GetWork.js
[1] dist/ts/test/Integration/GetWorks.js -> dist/babel/test/Integration/GetWorks.js
[1] dist/ts/test/Integration/GetWorksByPublicKey.js -> dist/babel/test/Integration/GetWorksByPublicKey.js
[1] dist/ts/test/Integration/Helper.js -> dist/babel/test/Integration/Helper.js
[1] dist/ts/test/Integration/PostWork.js -> dist/babel/test/Integration/PostWork.js
[1] dist/ts/test/Integration/SecurityHeaders.js -> dist/babel/test/Integration/SecurityHeaders.js
[1] dist/ts/test/Keys.js -> dist/babel/test/Keys.js
[1] dist/ts/test/PrepareDB.js -> dist/babel/test/PrepareDB.js
[1] dist/ts/test/Script.js -> dist/babel/test/Script.js
[1] The optional dependency chokidar failed to install and is required for --watch. Chokidar is likely not supported on your platform.
[1] Error: Cannot find module 'chokidar'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
[1]     at Module.require (internal/modules/cjs/loader.js:636:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.requireChokidar (/usr/src/app/node_modules/babel-cli/lib/babel/util.js:85:12)
[1]     at module.exports (/usr/src/app/node_modules/babel-cli/lib/babel/dir.js:73:25)
[1]     at Object.<anonymous> (/usr/src/app/node_modules/babel-cli/lib/babel/index.js:129:1)
[1]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[1]     at Module.load (internal/modules/cjs/loader.js:598:32)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! @po.et/node@1.0.3 watch-babel: `cp .babelrc dist/ts && babel -w dist/ts/ -d dist/babel --copy-files`
npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the @po.et/node@1.0.3 watch-babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-19T19_38_17_822Z-debug.log
[1] npm run watch-babel exited with code 1
--> Sending SIGTERM to other processes..
[0] tsc -w exited with code SIGTERM
--> Sending SIGTERM to other processes..
[2] nodemon --delay 10 dist/babel/src exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @po.et/node@1.0.3 watch: `concurrently --kill-others "tsc -w"  "npm run watch-babel" "nodemon --delay 10 dist/babel/src"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @po.et/node@1.0.3 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-19T19_38_17_971Z-debug.log
```

**Comment by warrenv** [comment]
We have `optional` npm packages set to false in `.npmrc` to prevent package file changes
due to having a mixed team of  macos and linux users.

Try this command in the container: `npm --optional true install`

**Comment by kennylavender** [comment]
That solved it thanks @warrenv! Should probably add that to the docs, not sure if that would belong in local-dev docs or node?

**Comment by warrenv** [comment]
you're welcome!
...or we could modify the node's `Dockerfile` to include the option. It seems to work with `npm ci` as well.

**Comment by kennylavender** [comment]
I will try npm ci further, npm ci seemed much slower at first, but just tried it again and it was about the same.
