### ISSUE TITLE
Debug Compilation Error in IPFS Helper

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#726]
pull request: https://github.com/poetapp/node/pull/721

travis: https://travis-ci.org/poetapp/node/builds/450997236?utm_source=github_status&utm_medium=notification

It's getting this error repeatedly in travis function tests.

```
https://github.com/poetapp/node/blob/master/src/Helpers/IPFS.ts#L6[2018-11-05T18:54:34.456Z] ERROR (164 on 6e2df593ea82): Upload next claim failure
    module: "StorageWriter"
    file: "Router"
    method: "onStorageWriterStoreNextClaim"
    error: {
      "stack": [
        "ReferenceError: Time_1 is not defined"
        "    at Object.addText (/usr/src/app/src/Helpers/IPFS.ts:35:15)"
        "    at ClaimController.uploadClaim (/usr/src/app/src/StorageWriter/ClaimController.ts:59:78)"
        "    at ClaimController.storeClaim (/usr/src/app/src/StorageWriter/ClaimController.ts:63:37)"
        "    at /usr/src/app/node_modules/ramda/src/internal/_pipeP.js:5:16"
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
      "message": "Time_1 is not defined"
      "type": "ReferenceError"
    }
```

Seems to possibly be coming from this line: https://github.com/poetapp/node/blob/master/src/Helpers/IPFS.ts#L6
```ts
import { minutesToMiliseconds } from './Time'
```
References this file: https://github.com/poetapp/node/blob/master/src/Helpers/Time.ts

I have also tried
```ts
import { minutesToMiliseconds } from 'Helpers/Time'
```
but then tslint complains `Imported lower-level module into non-root directory using an absolute path. Please use a relative path: import { minutesToMiliseconds } from 'Helpers/Time'`

**Comment by kennylavender** [comment]
Copying the minutesToMiliseconds function to the IPFS file, see if that fixes the error to see if its truly the import causing the issue: https://github.com/poetapp/node/pull/721/commits/b3d80187aa16af6818f09e5396e097474d51bde9

**Comment by kennylavender** [comment]
It was due to trying to pass an IPFS instance via DI `toConstant`
